# ===========================================
# Nyx File Generation Examples
# ===========================================
# Demonstrates how to generate various file formats

import generator
import io

fn main() {
    print("Nyx File Generation Examples");
    print("============================\n");
    
    # ===========================================
    # TEXT-BASED FILES
    # ===========================================
    
    print("1. Generating text-based files...");
    
    # Generate plain text file
    generator::generate_txt("output/sample.txt", "Hello from Nyx!\nThis is a plain text file.");
    print("  ✓ Generated sample.txt");
    
    # Generate Markdown file
    let md_sections = [
        {heading: "Introduction", content: "This is a Markdown document generated by Nyx.", level: 2},
        {heading: "Features", content: "- Easy to use\n- Multiple formats\n- Fast generation", level: 2},
        {heading: "Conclusion", content: "Nyx makes file generation simple!", level: 2}
    ];
    generator::generate_md("output/document.md", "My Nyx Document", md_sections);
    print("  ✓ Generated document.md");
    
    # Generate CSV file
    let csv_headers = ["Name", "Age", "City", "Occupation"];
    let csv_rows = [
        ["Alice Johnson", "30", "New York", "Engineer"],
        ["Bob Smith", "25", "Los Angeles", "Designer"],
        ["Carol Davis", "35", "Chicago", "Manager"],
        ["David Wilson", "28", "Houston", "Developer"]
    ];
    generator::generate_csv("output/data.csv", csv_headers, csv_rows, ",");
    print("  ✓ Generated data.csv");
    
    # Generate RTF file
    generator::generate_rtf("output/document.rtf", "Rich Text Document", 
        "This is a rich text document.\n\nIt supports multiple paragraphs and formatting.", 
        24);
    print("  ✓ Generated document.rtf");
    
    print("");
    
    # ===========================================
    # IMAGE FILES
    # ===========================================
    
    print("2. Generating image files...");
    
    # Generate SVG image
    let svg_elements = [
        {type: "rect", x: 10, y: 10, width: 280, height: 180, fill: "lightblue", stroke: "navy", stroke_width: 2},
        {type: "circle", cx: 150, cy: 100, r: 40, fill: "coral"},
        {type: "circle", cx: 100, cy: 80, r: 25, fill: "gold"},
        {type: "circle", cx: 200, cy: 80, r: 25, fill: "gold"},
        {type: "line", x1: 120, y1: 130, x2: 180, y2: 130, stroke: "navy", stroke_width: 3},
        {type: "text", x: 150, y: 30, content: "Happy SVG!", fill: "navy", font_size: 20, font_family: "Arial"}
    ];
    generator::generate_svg("output/image.svg", 300, 200, svg_elements);
    print("  ✓ Generated image.svg");
    
    # Generate PNG image (requires Python PIL)
    fn draw_png(img) {
        return [
            {cmd: "rectangle", xy: [[0, 0], [300, 200]], fill: "lightgreen"},
            {cmd: "ellipse", xy: [[50, 50], [150, 150]], fill: "blue", outline: "darkblue"},
            {cmd: "ellipse", xy: [[150, 50], [250, 150]], fill: "red", outline: "darkred"},
            {cmd: "text", xy: [80, 170], text: "Nyx Graphics!", fill: "black", font_size: 20}
        ];
    }
    
    try {
        generator::generate_png("output/image.png", 300, 200, draw_png);
        print("  ✓ Generated image.png");
    } catch e {
        print("  ✗ PNG generation requires Python PIL: " + str(e));
    }
    
    print("");
    
    # ===========================================
    # DOCUMENT FILES
    # ===========================================
    
    print("3. Generating document files...");
    
    # Generate PDF (requires Python reportlab)
    let pdf_content = [
        {type: "heading", text: "Welcome to Nyx", level: 1},
        {type: "paragraph", text: "This is a PDF document generated by the Nyx programming language."},
        {type: "spacer", height: 0.2},
        {type: "heading", text: "Features", level: 2},
        {type: "bullet", text: "Easy file generation"},
        {type: "bullet", text: "Multiple format support"},
        {type: "bullet", text: "Clean API"},
        {type: "spacer", height: 0.2},
        {type: "heading", text: "Conclusion", level: 2},
        {type: "paragraph", text: "Nyx makes document generation simple and powerful."}
    ];
    
    try {
        generator::generate_pdf("output/document.pdf", "Nyx Document", pdf_content, null);
        print("  ✓ Generated document.pdf");
    } catch e {
        print("  ✗ PDF generation requires Python reportlab: " + str(e));
    }
    
    # Generate DOCX (requires Python python-docx)
    let docx_sections = [
        {
            heading: "Introduction",
            paragraphs: [
                "This is a Microsoft Word document generated by Nyx.",
                "It demonstrates the document generation capabilities."
            ],
            level: 1
        },
        {
            heading: "Technical Details",
            paragraphs: [
                "Nyx uses Python libraries under the hood for complex formats.",
                "The API is simple and intuitive."
            ],
            level: 2
        }
    ];
    
    try {
        generator::generate_docx("output/document.docx", "Nyx Word Document", docx_sections);
        print("  ✓ Generated document.docx");
    } catch e {
        print("  ✗ DOCX generation requires Python python-docx: " + str(e));
    }
    
    print("");
    
    # ===========================================
    # SPREADSHEET FILES
    # ===========================================
    
    print("4. Generating spreadsheet files...");
    
    # Generate XLSX (requires Python openpyxl)
    let xlsx_sheets = [
        {
            name: "Sales Data",
            headers: ["Month", "Revenue", "Expenses", "Profit"],
            data: [
                ["January", 50000, 30000, 20000],
                ["February", 55000, 32000, 23000],
                ["March", 60000, 35000, 25000],
                ["April", 58000, 33000, 25000]
            ]
        },
        {
            name: "Summary",
            headers: ["Metric", "Value"],
            data: [
                ["Total Revenue", 223000],
                ["Total Expenses", 130000],
                ["Total Profit", 93000]
            ]
        }
    ];
    
    try {
        generator::generate_xlsx("output/spreadsheet.xlsx", xlsx_sheets);
        print("  ✓ Generated spreadsheet.xlsx");
    } catch e {
        print("  ✗ XLSX generation requires Python openpyxl: " + str(e));
    }
    
    print("");
    
    # ===========================================
    # PRESENTATION FILES
    # ===========================================
    
    print("5. Generating presentation files...");
    
    # Generate PPTX (requires Python python-pptx)
    let pptx_slides = [
        {
            title: "Introduction to Nyx",
            content: [
                "A modern programming language",
                "Multiple paradigms supported",
                "High performance"
            ],
            layout: "title_and_content"
        },
        {
            title: "File Generation Features",
            content: [
                "Text formats: TXT, MD, CSV, RTF",
                "Images: SVG, PNG, JPG, ICO",
                "Documents: PDF, DOCX, ODT",
                "Spreadsheets: XLSX, ODS",
                "Presentations: PPTX, ODP"
            ],
            layout: "title_and_content"
        },
        {
            title: "Conclusion",
            content: [
                "Easy to use",
                "Powerful capabilities",
                "Extensible design"
            ],
            layout: "title_and_content"
        }
    ];
    
    try {
        generator::generate_pptx("output/presentation.pptx", "Nyx File Generation", pptx_slides);
        print("  ✓ Generated presentation.pptx");
    } catch e {
        print("  ✗ PPTX generation requires Python python-pptx: " + str(e));
    }
    
    print("");
    
    # ===========================================
    # UNIFIED INTERFACE
    # ===========================================
    
    print("6. Using unified interface...");
    
    # Generate using unified interface (auto-detects format)
    let unified_data = {
        title: "Auto-Generated",
        sections: [
            {heading: "Section 1", content: "Content 1", level: 2}
        ]
    };
    generator::generate_file("output/unified.md", null, unified_data);
    print("  ✓ Generated unified.md (auto-detected format)");
    
    print("");
    
    # ===========================================
    # BATCH GENERATION
    # ===========================================
    
    print("7. Batch generation...");
    
    let batch_specs = [
        {
            path: "output/batch1.txt",
            format: "txt",
            data: "Batch generated text file 1"
        },
        {
            path: "output/batch2.txt",
            format: "txt",
            data: "Batch generated text file 2"
        },
        {
            path: "output/batch.csv",
            format: "csv",
            data: {
                headers: ["ID", "Name"],
                rows: [["1", "Item 1"], ["2", "Item 2"]],
                delimiter: ","
            }
        }
    ];
    
    let batch_results = generator::generate_files(batch_specs);
    print("  ✓ Generated " + str(len(batch_results)) + " files in batch");
    
    print("");
    
    # ===========================================
    # TEMPLATE-BASED GENERATION
    # ===========================================
    
    print("8. Template-based generation...");
    
    # Create a template
    let template = "Hello {{name}}!\n\nYou are {{age}} years old.\nYour email is {{email}}.";
    io::write_file("output/template.txt", template);
    
    # Generate from template
    let vars = {
        name: "Alice",
        age: "30",
        email: "alice@example.com"
    };
    generator::generate_from_template("output/template.txt", "output/from_template.txt", vars);
    print("  ✓ Generated from_template.txt from template");
    
    print("");
    print("All examples completed!");
    print("\nNote: Some formats require Python libraries:");
    print("  - PNG/JPG/ICO: pip install Pillow");
    print("  - PDF: pip install reportlab");
    print("  - DOCX: pip install python-docx");
    print("  - ODT/ODS/ODP: pip install odfpy");
    print("  - XLSX: pip install openpyxl");
    print("  - PPTX: pip install python-pptx");
}

# Run examples
main();
